version: 2.1
jobs:
  build:
    # working_directory: ~/mern-starter
    docker:
      - image: aslushnikov/playwright:bionic
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-all-packages
          command: 'npm ci'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./.local-browsers
      - run:
          name: test
          command: xvfb-run --auto-servernum npm run test